name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: upload file
      uses: actions/upload-artifact@v4.6.0
      with:
            name: requirements file
            path: requirements.txt

    - name: download path
      uses: actions/download-artifact@v4.1.8
      with:
            name: requirements file

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
